language: clojure
sudo:     required
dist:     trusty
jdk:
- oraclejdk8
before_install:
- wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod +x lein
script: ./lein modules test && ./lein modules doo node test-none once
