language: clojure
sudo: required
dist: trusty
addons:
  firefox: latest
jdk:
  - oraclejdk8
env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=:99.0
before_install:
  - pip install --user awscli
  - export PATH=$(pwd):$PATH
  - nvm install 5
  - npm install -g karma karma-cli karma-chrome-launcher karma-firefox-launcher karma-cljs-test
  - sh -e /etc/init.d/xvfb start
script: bin/travis.sh
